name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
          
      - name: Sauvegarder le code, générer Android, puis restaurer
        run: |
          # 1. Sauvegarde de ton application
          mkdir -p safety_backup
          cp lib/main.dart safety_backup/main.dart
          
          # 2. Génération / mise à jour de la structure Android
          flutter create . --org com.cyril.muscu --project-name carnet_musculation --platforms=android --overwrite
          
          # 3. Restauration de ton application
          cp safety_backup/main.dart lib/main.dart
          
      - name: Installation des dépendances et compilation APK
        run: |
          flutter pub get
          flutter build apk --release
          
      - name: Téléverser l'APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
          
